name: dictionary
description: "A new Flutter project."

version: 1.0.0+2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.7
  logger: ^2.0.2+1
  http: ^1.2.0
  supabase_flutter: ^2.3.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  mocktail: ^1.0.3
  envied: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9
  envied_generator: ^0.5.3


flutter:
  uses-material-design: true


